name: Deploy Application

on:
  push:
    branches:
      - main
      - develop
      - feature/*

jobs:
  deploy-app:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        SSH_HOST: ${{ secrets.SSH_HOST }}
        SSH_USER: ${{ secrets.SSH_USER }}
      run: |
        # Start the SSH agent
        eval $(ssh-agent -s)
        # Add the SSH private key to the SSH agent
        echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
        # Ensure the .ssh directory exists
        mkdir -p ~/.ssh
        # Add the SSH host to known hosts
        ssh-keyscan $SSH_HOST >> ~/.ssh/known_hosts
        # Print the SSH_HOST to verify it's set correctly
        echo "SSH Host: $SSH_HOST"

    - name: Deploy Application
      env:
        SSH_HOST: ${{ secrets.SSH_HOST }}
        SSH_USER: ${{ secrets.SSH_USER }}
        DEPLOY_PATH: ${{ secrets.DEPLOY_PATH }}
      run: |
        ssh -vvv $SSH_USER@$SSH_HOST << 'EOF'
          sudo su - node -c "
            # Create deployment directory if it doesn't exist
            mkdir -p hiii
        EOF

